version: '1.0'

services:
  apache2:
    build:
      dockerfile: docker-config/Dockerfile
    container_name: mini-twitter-server
    ports:
      - '80:80'
    links:
      - mariadb:mariadb
    volumes:
      - './:/var/www/html'
    networks:
      mini-twitter-network:
        aliases:
          - apache2

  mariadb:
    image: mariadb:10.9.1-rc
    container_name: mariadb-server
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - ./docker-config/database/init:/docker-entrypoint-initdb.d
      - ./docker-config/database/data:/var/lib/mysql
    networks:
      mini-twitter-network:
        aliases:
          - mariadb

networks:
  mini-twitter-network:
    name: mini-twitter-net
    driver: bridge
    ipam:
      driver: default
